# This file was generated by GoReleaser. DO NOT EDIT.
cask "enver" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "c1372c08515aea10ad2b5f0db647beba9eef0f0a23aa60615201c22a04bf783b"
      url "https://github.com/neiromaster/enver/releases/download/v#{version}/enver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d8d12c053d34d6255912e3d7e24e1d90eaa072519ed3409b77c274df7f45af8"
      url "https://github.com/neiromaster/enver/releases/download/v#{version}/enver_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d2103113ccb4618238d3bd33fc29721cc9cdeda50722268146e85f282bdde289"
      url "https://github.com/neiromaster/enver/releases/download/v#{version}/enver_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "95bc93ebdaff692d650c48534a571d186eac0107deb956a436f294cb7e65ce5f"
      url "https://github.com/neiromaster/enver/releases/download/v#{version}/enver_#{version}_linux_arm64.tar.gz"
    end
  end

  name "enver"
  desc "Inject environment variables from layered YAML profiles into any command"
  homepage "https://github.com/neiromaster/enver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "enver"
  binary "enverx"
  bash_completion "completions/enver.bash"
  fish_completion "completions/enver.fish"
  zsh_completion "completions/enver.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

end
