# This file was generated by GoReleaser. DO NOT EDIT.
cask "enver" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "77fbd047e4362441fdce27bd1c382fc4b08e9adf642dc4cb73be93b4c8f73170"
      url "https://github.com/neiromaster/enver/releases/download/v#{version}/enver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "40a8b336bb313b093710b378b34939d4b4a03e2dce71ffaf3074be2524a9b51b"
      url "https://github.com/neiromaster/enver/releases/download/v#{version}/enver_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e34d49439bd2ff3e8d63b7d41495431c2aa4073038b8f709cd12618ef90c4070"
      url "https://github.com/neiromaster/enver/releases/download/v#{version}/enver_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0eb33b35fc596c6153e5489b47facf0306d81f363233bc4197cd0acdc439230"
      url "https://github.com/neiromaster/enver/releases/download/v#{version}/enver_#{version}_linux_arm64.tar.gz"
    end
  end

  name "enver"
  desc "Inject environment variables from layered YAML profiles into any command"
  homepage "https://github.com/neiromaster/enver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "enver"
  binary "enverx"
  bash_completion "completions/enver.bash"
  fish_completion "completions/enver.fish"
  zsh_completion "completions/enver.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

end
