# This file was generated by GoReleaser. DO NOT EDIT.
cask "enver" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "a2be52a8efa39276738163277b24aeff16125d5211198b31ebb9c8ef6fa00992"
      url "https://github.com/neiromaster/enver/releases/download/v#{version}/enver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bfbaeb4a51000bb399b18b83ce928d9aa29478bfcbd2a0b4333a8fbd60f858d"
      url "https://github.com/neiromaster/enver/releases/download/v#{version}/enver_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b157d7e4f147e1cd8dc444062b803966ba19aca7cb910b20a0a962cfd13fe093"
      url "https://github.com/neiromaster/enver/releases/download/v#{version}/enver_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "56766c2fdf7fc3f006749e888a81d66d1619cb7bbeb600b0b80c029347026fac"
      url "https://github.com/neiromaster/enver/releases/download/v#{version}/enver_#{version}_linux_arm64.tar.gz"
    end
  end

  name "enver"
  desc "Inject environment variables from layered YAML profiles into any command"
  homepage "https://github.com/neiromaster/enver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "enver"
  binary "enverx"
  bash_completion "completions/enver.bash"
  fish_completion "completions/enver.fish"
  zsh_completion "completions/enver.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

end
